token_url1 = "https://useraction.zee5.com/tokennd"
search_api_endpoint = "https://gwapi.zee5.com/content/details/"
platform_token = "https://useraction.zee5.com/token/platform_tokens.php?platform_name=web_app"
token_url2 = "https://useraction.zee5.com/token"
stream_baseurl = "https://zee5vodnd.akamaized.net"
